---
- name: Copy Filebeat configuration.
  ansible.builtin.template:
    src: "{{ filebeat_template }}"
    dest: "/etc/filebeat/filebeat.yml"
    owner: root
    group: root
    mode: "0644"
  notify: Restart filebeat
